name: Release

on:
  push:
    branches:
      - main

jobs:
  docker-api:
    name: Docker Image (API)
    runs-on: ubuntu-latest
    steps:
      - name: Setup Taskfile
        uses: arduino/setup-task@main
        with:
          version: "3.x"
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "~1.19"
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: markliederbach/finna-api,ghcr.io/${{ github.repository }}-api
          tags: |
            type=semver,pattern=v0.0.2
            type=semver,pattern=v0.0
            type=semver,pattern=v0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/api/Dockerfile
          build-args: |
            VERSION=v0.0.2
